
package com.v2com.iws10.axon.template.service.soap.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EmployeeServiceTopDownImpService", targetNamespace = "http://topdown.server.jaxws.v2com.com/", wsdlLocation = "http://localhost:8085/employeeservicetopdown?wsdl")
public class EmployeeServiceTopDownImpService
    extends Service
{

    private final static URL EMPLOYEESERVICETOPDOWNIMPSERVICE_WSDL_LOCATION;
    private final static WebServiceException EMPLOYEESERVICETOPDOWNIMPSERVICE_EXCEPTION;
    private final static QName EMPLOYEESERVICETOPDOWNIMPSERVICE_QNAME = new QName("http://topdown.server.jaxws.v2com.com/", "EmployeeServiceTopDownImpService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8085/employeeservicetopdown?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EMPLOYEESERVICETOPDOWNIMPSERVICE_WSDL_LOCATION = url;
        EMPLOYEESERVICETOPDOWNIMPSERVICE_EXCEPTION = e;
    }

    public EmployeeServiceTopDownImpService() {
        super(__getWsdlLocation(), EMPLOYEESERVICETOPDOWNIMPSERVICE_QNAME);
    }

    public EmployeeServiceTopDownImpService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EMPLOYEESERVICETOPDOWNIMPSERVICE_QNAME, features);
    }

    public EmployeeServiceTopDownImpService(URL wsdlLocation) {
        super(wsdlLocation, EMPLOYEESERVICETOPDOWNIMPSERVICE_QNAME);
    }

    public EmployeeServiceTopDownImpService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EMPLOYEESERVICETOPDOWNIMPSERVICE_QNAME, features);
    }

    public EmployeeServiceTopDownImpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmployeeServiceTopDownImpService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EmployeeServiceTopDown
     */
    @WebEndpoint(name = "EmployeeServiceTopDownPort")
    public EmployeeServiceTopDown getEmployeeServiceTopDownPort() {
        return super.getPort(new QName("http://topdown.server.jaxws.v2com.com/", "EmployeeServiceTopDownPort"), EmployeeServiceTopDown.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmployeeServiceTopDown
     */
    @WebEndpoint(name = "EmployeeServiceTopDownPort")
    public EmployeeServiceTopDown getEmployeeServiceTopDownPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://topdown.server.jaxws.v2com.com/", "EmployeeServiceTopDownPort"), EmployeeServiceTopDown.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EMPLOYEESERVICETOPDOWNIMPSERVICE_EXCEPTION!= null) {
            throw EMPLOYEESERVICETOPDOWNIMPSERVICE_EXCEPTION;
        }
        return EMPLOYEESERVICETOPDOWNIMPSERVICE_WSDL_LOCATION;
    }

}
