
package com.v2com.iws10.axon.template.service.soap.client;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EmployeeServiceTopDown", targetNamespace = "http://topdown.server.jaxws.v2com.com/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmployeeServiceTopDown {


    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "countEmployeesResponse", targetNamespace = "http://topdown.server.jaxws.v2com.com/", partName = "countEmployeesResponse")
    @Action(input = "http://topdown.server.jaxws.v2com.com/EmployeeServiceTopDown/countEmployeesRequest", output = "http://topdown.server.jaxws.v2com.com/EmployeeServiceTopDown/countEmployeesResponse")
    public int countEmployees();

}
