<definitions xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" 
  xmlns:wsp="http://www.w3.org/ns/ws-policy" 
  xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" 
  xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" 
  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
  xmlns:tns="http://topdown.server.jaxws.v2com.com/" 
  xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
  xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://topdown.server.jaxws.v2com.com/" name="EmployeeServiceTopDownImpService">
  <types>
    <xsd:schema>
      <xsd:import namespace="http://topdown.server.jaxws.v2com.com/" schemaLocation="http://localhost:8085/employeeservicetopdown?xsd=1"/>
    </xsd:schema>
  </types>
  <message name="countEmployees"/>
  <message name="countEmployeesResponse">
    <part name="countEmployeesResponse" element="tns:countEmployeesResponse"/>
  </message>
  <portType name="EmployeeServiceTopDown">
    <operation name="countEmployees">
      <input wsam:Action="http://topdown.server.jaxws.v2com.com/EmployeeServiceTopDown/countEmployeesRequest" message="tns:countEmployees"/>
      <output wsam:Action="http://topdown.server.jaxws.v2com.com/EmployeeServiceTopDown/countEmployeesResponse" message="tns:countEmployeesResponse"/>
    </operation>
  </portType>
  <binding name="EmployeeServiceTopDownPortBinding" type="tns:EmployeeServiceTopDown">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
    <operation name="countEmployees">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="EmployeeServiceTopDownImpService">
    <port name="EmployeeServiceTopDownPort" binding="tns:EmployeeServiceTopDownPortBinding">
      <soap:address location="http://localhost:8085/employeeservicetopdown"/>
    </port>
  </service>
</definitions>